version: "3.7"
services:
  postgres:
    container_name: postgres
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Please set POSTGRES_PASSWORD}
    user: postgres
    network_mode: "host"
  datomic:
    build:
      context: datomic
    container_name: datomic
    image: spa-monkey_datomic:latest
    restart: unless-stopped
    init: true
    network_mode: "host"
    ports:
      - "4334:4334"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Please set POSTGRES_PASSWORD}
