version: "3.7"
services:
  postgres:
    container_name: postgres
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  datomic:
    build:
      context: datomic
      args:
        DATOMIC_HTTP_USERNAME: $DATOMIC_HTTP_USERNAME
        DATOMIC_HTTP_PASSWORD: $DATOMIC_HTTP_PASSWORD
    container_name: datomic
    image: spa-monkey_datomic:latest
    restart: unless-stopped
    init: true
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - DATOMIC_LICENSE_KEY=$DATOMIC_LICENSE_KEY
